
#! /bin/bash

echo "Testing add_abs on 5 and 10 produces output:"
./add_abs <<< "5 10"
echo ""
echo "Testing add_abs on 0 and 7 produces output:"
./add_abs <<< "0 7"
echo ""
echo "Testing add_abs on -8 and -4 produces output:"
./add_abs <<< "-8 -4"
echo ""
echo "Testing add_abs on -2 and 0 produces output:"
./add_abs <<< "-2 0"
echo ""
echo "Testing add_abs on -3 and 6 produces output:"
./add_abs <<< "-3 6"
echo ""
echo "Testing add_abs on 9 and -11 produces output:"
./add_abs <<< "9 -11"
echo ""
echo "Testing add_abs on 0 and 0 produces output:"
./add_abs <<< "0 0"
echo ""
echo "Testing add_abs on -5 and 2 produces output:"
./add_abs <<< "-5 2"
echo ""
